{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   AssertionError: assert 'nada se compara' in '\u00d7\\nHuman verification has failed! Please try again.'\n    +  where '\u00d7\\nHuman verification has failed! Please try again.' = <bound method ShampooPage.errorWithoutCode of <POM.ShampooPage.ShampooPage object at 0x000001DDE4816F10>>()\n    +    where <bound method ShampooPage.errorWithoutCode of <POM.ShampooPage.ShampooPage object at 0x000001DDE4816F10>> = <POM.ShampooPage.ShampooPage object at 0x000001DDE4816F10>.errorWithoutCode\n", "test_name": "test_Give_Review", "rerun": "0"}}, "suite_name": "test_Give_Review.py"}}}, "date": "January 27, 2022", "start_time": 1643303813.0636828, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}